<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Begin_inspection_model extends CI_Model {

    public $table = 'begin_inspection';
    public $id = 'id';
    public $cat = 'parent_id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    function get_index(){
        $query ="
        select 
            m.*, cat.category as category_name, prod.product_category as product_name,
            user.company, man.manufacture_name, u.description as unit_system, s.schedule
        from 
            mst_product m
            left join category cat ON m.category_id = cat.id 
            left join product_category prod ON m.product_category_id = prod.id
            left join end_user user ON m.end_user_id = user.id
            left join manufacture man ON m.manufacture_id = man.id
            left join hp_unit u ON m.unit_system_id = u.id
            left join hp_schedule s ON m.inspection_schedule_id = s.id";

        $result = $this->db->query($query)->result();
        
        return $result;

    }

    function get_begin_inspection(){
        $query = "
            select 
                bi.*, loc.location_name, ins.inspector_name               
            from 
                begin_inspection bi                        
            left join location loc ON bi.location_id = loc.id
            left join inspector ins ON bi.inspector_id = ins.id
            ";
        //die($query);
        $result = $this->db->query($query)->result()->row();
        
        return $result;
    }

    function get_detail_inspection($id){
        $query = "
            select 
                b.*, l.location_name, i.inspector_name
            from 
                begin_inspection b                
                left join location l ON b.location_id = l.id
                left join inspector i ON b.inspector_id = i.id
            where
                b.parent_id = ".$id;
        //echo $query;die();
        $result = $this->db->query($query)->result();
        return $result;
    }

    function cek_data_complete($parent_id)
    {
        $query = "SELECT * FROM ".$this->table." WHERE parent_id = ".$parent_id." order by id desc";        
        $result = $this->db->query($query)->row();
        return $result;   
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, array('uid' => $this->session->userdata('user_id')))->result();
    }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, array('uid' => $this->session->userdata('user_id')))->num_rows();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        //$this->db->or_like('mst_product_id', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        //$this->db->or_like('mst_product_id', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        //echo $id.'<pre>';print_r($data);die();
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) { 
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pelanggan_model.php */
/* Location: ./application/models/Pelanggan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-1 09:11:35 */