<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Header_inspection_model extends CI_Model {

    public $table = 'header_inspection';
    public $id = 'id';
    public $cat = 'category_id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    function index(){
        $query ="
        select 
            m.*, cat.category as category_name, prod.product_category as product_name,
            user.company, man.manufacture_name, u.description as unit_system, s.schedule
        from 
            mst_product m
            left join category cat ON m.category_id = cat.id 
            left join product_category prod ON m.product_category_id = prod.id
            left join end_user user ON m.end_user_id = user.id
            left join manufacture man ON m.manufacture_id = man.id
            left join hp_unit u ON m.unit_system_id = u.id
            left join hp_schedule s ON m.inspection_schedule_id = s.id";

        $result = $this->db->query($query)->result();
        
        return $result;
    }

    // get all
    function get_all() {
        $query ="
            select 
                h.*, p.product_category as category_name, c.category as product_name, m.serial_number, 
                m.asset_number, u.company, man.manufacture_name
            from 
                header_inspection h
                left join product_category p ON h.category_id = p.id
                left join mst_product m ON h.product_id = m.id
                left join category c ON m.category_id = c.id
                left join end_user u ON m.end_user_id = u.id
                left join manufacture man ON m.manufacture_id = man.id
            ";

        $result = $this->db->query($query)->result();
        
        return $result;
    }

    function get_by_id_product($id){
        $query = "select category_id from header_inspection where id = ".$id;
        $result = $this->db->query($query)->result();
        
        return $result;
    }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, array('uid' => $this->session->userdata('user_id')))->num_rows();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        //$this->db->or_like('mst_product_id', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        //$this->db->or_like('mst_product_id', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pelanggan_model.php */
/* Location: ./application/models/Pelanggan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-1 09:11:35 */