<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Inspector_model extends CI_Model {

    public $table = 'inspector';
    public $id = 'id';
    public $cat = 'inspector_name';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all_x() {
        $this->db->select('distinct(i.inspector_name), i.id, i.manufacture_id, m.manufacture_name', false);
        $this->db->from('inspector as i');
        $this->db->join('manufacture as m', 'i.manufacture_id = m.id');
        $this->db->join('end_user as e', 'i.link_to_user = e.id');

        return $this->db->get_where($this->table)->result();
        //return $this->db->get_where($this->table, array('i.uid' => $this->session->userdata('user_id')))->result();
    }
    
    function get_all()
    {
        $uid = $this->session->userdata('user_id');
        $kueri = " 
            select i.*, m.manufacture_name, tb.username 
            from inspector i 
            left join manufacture m ON i.manufacture_id = m.id
            left join tb_users tb ON i.link_to_user = tb.id
                ";
     
        $result = $this->db->query($kueri)->result();

        return $result;
    }

    function get_rows() {
        $this->db->order_by($this->id, $this->order);
        //return $this->db->get_where($this->table)->num_rows();
        return $this->db->get_where($this->table, array('uid' => $this->session->userdata('user_id')))->num_rows();
    }

    // get data by id
    function get_by_idxxx($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_id($id)
    {
        $kueri = " 
            select i.*, m.manufacture_name, tb.username 
            from inspector i 
            left join manufacture m ON i.manufacture_id = m.id
            left join tb_users tb ON i.link_to_user = tb.id
            where i.id = ".$id;
            
        $result = $this->db->query($kueri)->result();

        return $result;
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('inspector_name', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('inspector_name', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Inspector_model.php */
/* Location: ./application/models/Inspector_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-20 11:09:25 */