<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Label_model extends CI_Model {

    public $table = 'label';
    public $id    = 'id';
    public $label = 'label_name';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get_where($this->table, array('uid' => $this->session->userdata('user_id')))->result();

        $kueri = " 
            SELECT 
                l.*, p.product_category       
            FROM 
                label l
                LEFT JOIN product_category p ON l.product_category_id = p.id
            WHERE 
                l.uid = ".$this->session->userdata('user_id');
        
        //echo $kueri; die();

        $result = $this->db->query($kueri)->result();

        return $result;
    }

    function cek_label($parent_id, $cat_id){
        $kueri = "SELECT 
                        m.product_category_id, l.*, v.label_value
                    FROM
                        mst_product m
                            LEFT JOIN
                        label l ON m.product_category_id = l.product_category_id
                        left join label_value v on m.product_category_id = v.product_category_id
                    WHERE                    
                        m.id = ".$parent_id." and l.product_category_id = ".$cat_id." GROUP BY l.label_name";
        
        //die('periksa:'.$kueri);
        $result = $this->db->query($kueri)->result();

        return $result;
    }
    
    function get_label_value($parent_id, $cat_id){
        $kueri = "SELECT 
                        m.product_category_id, v.label_name, v.label_value
                    FROM
                        mst_product m
                            LEFT JOIN
                        label_value v ON m.id = v.parent_id
                    WHERE
                        v.parent_id = ".$parent_id." AND v.product_category_id = ".$cat_id." GROUP BY v.label_name";
               
        //die('periksa:'.$kueri);
        return $result = $this->db->query($kueri)->result();
           
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('label_name', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('label_name', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {        
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Days_model.php */
/* Location: ./application/models/Days_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-19 09:43:57 */