<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Label_value_model extends CI_Model {

    public $table = 'label_value';
    public $id    = 'id';
    public $label = 'label_name';
    public $label_value = 'label_value';
    public $procat_id = 'product_category_id';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // insert data
    function insert($data) {        
        $this->db->insert($this->table, $data);
    }    

    function update_label_value($id, $procat, $label, $value){
        //$kueri = "UPDATE label_value SET label_value = '".$value."' WHERE label_name = '".$label."'";
        $kueri = "
            INSERT INTO 
                label_value (parent_id, product_category_id, label_name, label_value) 
            VALUES($id,$procat,'$label','$value')";

        //echo $kueri;die();

        $this->db->query($kueri);
    }        

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function del_by_procat_id($procatid){
        $this->db->where($this->procat_id, $procatid);
        $this->db->delete($this->table);
    }

    function get_value_by_id($id) {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get_where($this->table, array('uid' => $this->session->userdata('user_id')))->result();

        $kueri = " 
            SELECT * FROM label_value
            WHERE parent_id = ".$id." GROUP BY label_name";                

        $result = $this->db->query($kueri)->result();

        return $result;
    }

    function cek_value($id){
        $kueri = " 
            SELECT * 
            FROM label_value             
            WHERE product_category_id = ".$id." GROUP BY label_name"
            ;        
        $result = $this->db->query($kueri)->result();

        return $result;
    }

}

/* End of file Days_model.php */
/* Location: ./application/models/Days_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-19 09:43:57 */